### ISSUE TITLE
Makefile is badly made

### ISSUE THREAD

**Issue by bolt926** [gradetools/parliament-bomb#9]
Hard dependency on GCC, doesn't check for deps.

**Comment by spacefault** [comment]
As of now, the Makefile assumes you already have all dependencies through the Nix Shell. The Nix developer shell adds `gcc` as a `buildInput`, and adds the Python Dependencies to `python311Packages`. I understand that the hard Nix dependency can be a problem for some people, which is why we might have some alternatives for developers who don't want to, or can't use Nix.

Do you have any ideas on how we could potentially solve this? I'm thinking that we could add a part in the Makefile that detects the compiler and does specific compiler. For the dependency checking, I'll try to add that into the Makefile, and for the Nix problem we'll have alternate installation methods for people who are not using Nix.

I'll make a new branch for this also.

**Comment by caernarferon** [comment]
WE HAVE A MAKEFILE???

**Comment by bolt926** [comment]
Yes, we do. We also have the tools and files for a configure script because we actually know how to use good tools instead of Rust and Cargo.

**Comment by spacefault** [comment]
> WE HAVE A MAKEFILE???

The makefiles are needed for building `parliamentctl`, and some of the other C programs needed for core `parliamentctl` functions.

**Comment by spacefault** [comment]
No longer relevant, we are using `cargo build` to build ParliamentBomb.
